<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-CNPMFastFood-861dd747-ddd1-47ba-b710-07f2c34962b9</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="8.0.27" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.27" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.23" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.23" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.23" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.23" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.26" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Product\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Product\Menu.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\images\Products\BanhMi\" />
      <Folder Include="wwwroot\images\Products\Burger\" />
      <Folder Include="wwwroot\images\Products\Drink\" />
      <Folder Include="wwwroot\images\Products\FrenchFries\" />
      <Folder Include="wwwroot\images\Products\FriedChicken\" />
      <Folder Include="wwwroot\images\Products\GaRan\" />
      <Folder Include="wwwroot\images\Products\HotDog\" />
      <Folder Include="wwwroot\images\Products\MiLy\" />
      <Folder Include="wwwroot\images\Products\Pizza\" />
      <Folder Include="wwwroot\images\Products\Sandwich\" />
    </ItemGroup>

</Project>
